MVC Facebook/MVC Facebook/Controllers/CommentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MVC_Facebook.Data;
using MVC_Facebook.Models;
using MVC_Facebook.Models.Repository;

namespace MVC_Facebook.Controllers
{
    [Authorize(Roles = "Normal User")]
    public class CommentsController : Controller
    {
        private readonly ICommentRepository _commentRepository;

        public CommentsController(ICommentRepository commentRepository)
        {
            _commentRepository = commentRepository;
        }

        [HttpGet]
        public IActionResult showCommentPost(int id)
        {
            List<Comment> comments = _commentRepository.GetAll().Where(c => c.PostID == id && c.IsDeleted == false).Include(p => p.CommentOwner).OrderBy(c=>c.TimeStamp).ToList();
            return PartialView(comments);

        }

        public JsonResult AddComment([Bind("ID,Body,PostID,CommentOwnerID,IsDeleted")] Comment com)
        {
            string CurrentUserID = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            com.CommentOwnerID = CurrentUserID;
            _commentRepository.Add(com);
            return Json(com.PostID);
        }

        public JsonResult Delete(int id)
        {
            Comment comment = _commentRepository.GetById(id);
            if (comment == null)
            {
                return Json("");
            }
            comment = _commentRepository.Delete(id);
            return Json(comment.PostID);
        }

    }
}

MVC Facebook/MVC Facebook/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MVC_Facebook.Models;
using MVC_Facebook.Models.Repository;

namespace MVC_Facebook.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        private readonly IUserRepository _userRepository;
        private readonly UserManager<User> _userManager;

        public HomeController(IUserRepository userRepository
            , UserManager<User> userManager
            )
        {
            _userRepository = userRepository;
            _userManager = userManager;
        }
        public async Task<IActionResult> Index()
        {
            var userId = _userManager.GetUserId(User);
            var user = _userRepository.GetById(userId);
            if (await _userManager.IsInRoleAsync(user, "Admin"))
            {
                return RedirectToAction("Index", "Admin");
            }
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MVC Facebook/MVC Facebook/Controllers/PostsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MVC_Facebook.Data;
using MVC_Facebook.Models;
using MVC_Facebook.Models.Repository;

namespace MVC_Facebook.Controllers
{
    [Authorize(Roles = "Normal User")]
    public class PostsController : Controller
    {
        private readonly IPostRepository _postRepository;
        private readonly IUserRepository _userRepository;
        private readonly ILikeRepository _likeRepository;
        private readonly UserManager<User> _userManager;

        public PostsController(IPostRepository postRepository, UserManager<User> userManager,  IUserRepository userRepository, ILikeRepository likeRepository)
        {
            _postRepository = postRepository;
            _userManager = userManager;
            _userRepository = userRepository;
            _likeRepository = likeRepository;
        }

        [HttpGet]
        public IActionResult ProfilePosts(string id)
        {
            var user = _userRepository.GetByIdWithEagerLoading(id);
            var ListOfPosts = user.Posts.OrderByDescending(p => p.TimeStamp).ToList();
            return PartialView("PostsList", ListOfPosts);

        }

        // GET: Posts
        public IActionResult NewsFeed()
        {
            var userId = _userManager.GetUserId(User);
            var user = _userRepository.GetByIdWithEagerLoading(userId);
            var result = user.Posts.ToList();

            foreach (var item in user.Friends)
            {
                var tempPost = item.Receiver.Posts.Where(p => p.IsDeleted == false).ToList();
                if (!(tempPost is null))
                    result.AddRange(tempPost);
            }
            foreach (var item in user.FriendOf)
            {
                var tempPost = item.Sender.Posts.Where(p => p.IsDeleted == false).ToList();
                if (!(tempPost is null))
                    result.AddRange(tempPost);
            }
            var r = result.OrderByDescending(p => p.TimeStamp);
            return PartialView("PostsList", r);
        }

        [HttpPost]
        public IActionResult PostLike(int PostID, string LikeOwnerID, bool isDeleted)
        {
            _likeRepository.Add(new Like() { PostID = PostID, LikeOwnerID = LikeOwnerID, IsDeleted = isDeleted });
            return RedirectToAction("Index", "Home");
        }

        //GET: /Posts/ShowLikeOwners/PostID
        [HttpGet]
        public IActionResult ShowLikeOwners(int PostID)
        {
            //Step1: get all likes list by postID
            var likesList = _likeRepository.GetAll().Where(l => l.PostID == PostID && l.IsDeleted == false);
            //Step2: get all users by likeOwnerID in each item in like list derived from prev step
            var likeOwners = from User in _userRepository.GetAll()
                             from Like in likesList
                             where User.Id == Like.LikeOwnerID
                             select User;

            //try getting user's(SignedInUser) friends
            var currentUserID = _userManager.GetUserId(User);
            var user = _userRepository.GetByIdWithEagerLoading(currentUserID);
            ViewData["User"] = user;
            var allFriends = user.Friends.Select(f => f.Receiver).Union(user.FriendOf.Select(f => f.Sender));

            ViewData["AllFriends"] = allFriends;

            //Step3:return user model to the partial view
            return PartialView(likeOwners.ToList());
        }

        // GET: Posts/Create
        public IActionResult Create()
        {
            return PartialView();
        }

        // POST: Posts/Create
        [HttpPost]
        public JsonResult Create(string Body)
        {
            Post post = new Post();
            post.PostOwnerID = _userManager.GetUserId(User);
            post.Body = Body;
            _postRepository.Add(post);
            return Json("");
        }

        // GET: Posts/Delete/5
        public IActionResult Delete(int id)
        {
            var post = _postRepository.GetById(id);
            if (post == null)
            {
                return NotFound();
            }
            _postRepository.Delete(id);
            return Ok();
        }
           }
}

MVC Facebook/MVC Facebook/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="row">
    <div class="offset-1 col-8">
        <div id="createPost" class="rounded">
            <!--Filled from ajax function-->
        </div>
        <div id="newsfeed">
            <!--Filled from ajax function-->
        </div>
    </div>
    <div class="col-3">
        <div id="friendRequest">
            <!--Filled from ajax function-->
        </div>
        <div id="friendList">
            <!--Filled from ajax function-->
        </div>
    </div>
</div>

@section Scripts
{
    <script>

        $().ready(function () {
            loadCreatePost();
            refreshNewsfeed();
            refreshRequests();
            refreshFriendList();
        });

        function refreshNewsfeed() {
            $("#newsfeed").load("/Posts/NewsFeed");
        }
        function loadCreatePost() {
            $("#createPost").load("/Posts/Create");
        }
        function refreshRequests() {
            $("#friendRequest").load("../User/FriendRequestList");
        }
        function refreshFriendList() {
            $("#friendList").load("../User/FriendList");
        }
        function deletePost(btn,id) {
            $.get('../Posts/Delete/' + id);
            setTimeout(function () {
                refreshNewsfeed();
            }, 500);
        }
        function deleteComment(btn, id) {
            $.get('../Comments/Delete/' + id);
            setTimeout(function () {
                refreshNewsfeed();
            }, 500);
        }
        function addPost() {
            valBody = $.trim($("#createPostBox").val());
            if (valBody != '') {
                $.ajax({
                    method: 'POST',
                    url: '@Url.Action("Create","Posts")',
                    dataType: "json",
                    data: { Body: valBody },
                    success: function () {
                        setTimeout(function () {
                            refreshNewsfeed();
                            loadCreatePost();
                        }, 500);
                    },
                    error: function (xhr, status, error) {
                        alert("Erroooooooooooor");
                    }
                });
            }
        }

        function addComment(postId) {
            valBody = $.trim($("#commentbox_" + postId).val());
            if (valBody != '') {
                $.ajax({
                    method: 'POST',
                    url: '@Url.Action("addComment","Comments")',
                    dataType: "json",
                    data: { PostID: postId, Body: valBody },
                    success: function () {
                        setTimeout(function () {
                            refreshNewsfeed();
                        }, 500);
                    },
                    error: function (xhr, status, error) {
                        alert("Erroooooooooooor");
                    }
                });
            }
        }

        function ToggleLike(caller, id) {
            var toggle = $(caller).attr("data-mytoggle");
            var postID = $(caller).attr("data-postID");
            var likeOwnerID = $(caller).attr("data-likeOwnerID");
            var numOfLikes = $(`#${id}`).html();
            var isdeleted;
            if (toggle == "false") {
                $(caller).css("color", "blue");
                $(caller).html("<i class='fas fa-thumbs-down'></i> &nbsp;Unlike");
                $(caller).attr("data-mytoggle", "true");
                $(caller).attr("data-isDeleted", "false");
                isdeleted = $(caller).attr("data-isDeleted");
                $(`#${id}`).html(parseInt(numOfLikes) + 1);
            }
            else {
                $(caller).css("color", "black");
                $(caller).html("<i class='fas fa-thumbs-up'></i> &nbsp;Like");
                $(caller).attr("data-mytoggle", "false");
                $(caller).attr("data-isDeleted", "true");
                isdeleted = $(caller).attr("data-isDeleted");
                $(`#${id}`).html(parseInt(numOfLikes) - 1);
            }
            $.post('/Posts/PostLike',   // url
                { PostID: postID, LikeOwnerID: likeOwnerID, isDeleted: isdeleted }, // data to be submit
                function (data, status, jqXHR) {// success callback
                    console.log(status)
                }
            );


        }
        function ShowModal(postID, caller) {
            var numOfLikes = $(caller).html()
            if (numOfLikes != 0) {
                $.ajax({
                    url: "/Posts/ShowLikeOwners",
                    method: 'GET',
                    data: { PostID: postID },
                    success: function (result) {
                        $('#renderModal').html(result);
                        $('#likeOwnersModal').modal();
                    },
                    error: function (error, status, xhr) {
                        alert(status)
                    }
                })
            }
        };

        //from friend request list
        function getRespond(btn, myData, reloadPage = false) {
            var valueState = $(btn).attr("value");
            $.ajax({
                type: 'POST',
                dataType: 'json',
                url: '../User/RespondToFriendRequest/',
                data: { senderID: myData, friendshipStateResponse: valueState },
                success: function (newData) {
                    if (reloadPage == true) {
                        location.reload();
                    }
                    else {
                        refreshRequests();
                        refreshFriendList();
                    }
                },
                error: function (XMLHttpRequest, textStatus, errorThrown) {

                }
            });
        };
    </script>
}