MVC Facebook/MVC Facebook/Controllers/CommentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MVC_Facebook.Data;
using MVC_Facebook.Models;
using MVC_Facebook.Models.Repository;

namespace MVC_Facebook.Controllers
{
    [Authorize(Roles = "Normal User")]
    public class CommentsController : Controller
    {
        private readonly ICommentRepository _commentRepository;

        public CommentsController(ICommentRepository commentRepository)
        {
            _commentRepository = commentRepository;
        }

        [HttpGet]
        public IActionResult showCommentPost(int id)
        {
            List<Comment> comments = _commentRepository.GetAll().Where(c => c.PostID == id && c.IsDeleted == false).Include(p => p.CommentOwner).OrderBy(c=>c.TimeStamp).ToList();
            return PartialView(comments);

        }

        public JsonResult AddComment([Bind("ID,Body,PostID,CommentOwnerID,IsDeleted")] Comment com)
        {
            string CurrentUserID = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            com.CommentOwnerID = CurrentUserID;
            _commentRepository.Add(com);
            return Json(com.PostID);
        }

        public JsonResult Delete(int id)
        {
            Comment comment = _commentRepository.GetById(id);
            if (comment == null)
            {
                return Json("");
            }
            comment = _commentRepository.Delete(id);
            return Json(comment.PostID);
        }

    }
}

MVC Facebook/MVC Facebook/Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Routing;
using Microsoft.EntityFrameworkCore;
using MVC_Facebook.Models;
using MVC_Facebook.Models.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Security.Policy;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Hosting;
using System.IO;

namespace MVC_Facebook.Controllers
{

    [Authorize(Roles = "Normal User")]
    public class UserController : Controller
    {
        private readonly IUserRepository repository;
        private readonly IWebHostEnvironment _appEnvironment;
        private readonly IFriendshipRepository friendRepository;
        private readonly UserManager<User> UserManager;


        public UserController(IUserRepository _repository, UserManager<User> UserManager, IFriendshipRepository friendRepository, IWebHostEnvironment appEnvironment)
        {
            this.friendRepository = friendRepository;
            repository = _repository;
            this.UserManager = UserManager;
            this._appEnvironment = appEnvironment;
        }
        
        public IActionResult UserInfo()
        {
            string CurrentUserID = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            var user = repository.GetByIdWithEagerLoading(CurrentUserID);
            return PartialView(user);
        }

        [HttpGet]
        public IActionResult EditInfo()
        {
            string CurrentUserID = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            User currentUser = repository.GetByIdWithEagerLoading(CurrentUserID);
            return PartialView(currentUser);
        }

        [HttpPost]
        public JsonResult EditInfo(string ID,string Bio,string Status)//User u)
        {
            var user = repository.GetByIdWithEagerLoading(ID);
            user.Bio = Bio;
            user.Status = Status;

            repository.Update(user);
            return Json("");
        }

        [HttpGet]
        public async Task<JsonResult> getName(string search)
        {           
            List<User> users = repository.GetByName(search);
            string CurrentUserID = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            User currentUser = users.Find(p => p.Id == CurrentUserID);
            users.Remove(currentUser);
            List<User> normalUsers = new List<User>();
            for(int i=0;i<users.Count;i++)
            {
                if(!await UserManager.IsInRoleAsync(users[i], "Admin"))
                {
                    normalUsers.Add(users[i]);
                }
            }         
            return Json(normalUsers);
        }

        public IActionResult FriendList(string ID)
        {
            var CurrentUserLogin = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            var user = repository.GetByIdWithEagerLoading(CurrentUserLogin);
            var result = new List<User>();
            var ff = user.Friends;
            foreach (var item in ff)
                result.Add(item.Receiver);
            var fo = user.FriendOf;
            foreach (var item in fo)
                result.Add(item.Sender);

            return PartialView(result);
        }

        public IActionResult FriendRequestList()
        {
            var CurrentUserLogin = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            var requests = friendRepository.GetAll().Where(p => p.ReceiverID == CurrentUserLogin
                                                           && p.State == FriendshipState.Pending);
            var senderList = requests.Select(p => p.Sender);
            return PartialView("FriendRequestList", senderList.ToList());
        }

        [HttpPost]
        public JsonResult RespondToFriendRequest(string senderID, string friendshipStateResponse)
        {
            var currentUserId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            var requestSender = friendRepository.GetFriendship(senderID, currentUserId);

            switch (friendshipStateResponse)
            {
                case "Accepted":
                    requestSender.State = FriendshipState.Accepted;
                    break;
                case "Removed":
                    requestSender.State = FriendshipState.Removed;
                    break;
                default:
                    break;
            }
            friendRepository.Update(requestSender);

            return Json(requestSender);
        }

        [HttpPost]
        public async Task< JsonResult> ChangeProfile()
        {
            IFormFileCollection files = Request.Form.Files;
            string CurrentUserID = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            User currentUser = repository.GetAll().FirstOrDefault(p => p.Id == CurrentUserID);
            string imgExt = Path.GetExtension(files[0].FileName);
            if (imgExt == ".jpg" || imgExt == ".PNG" || imgExt == ".png" || imgExt == ".JPG")
            {
                var newName = $"{CurrentUserID}_{files[0].FileName}";
                var saveImg = Path.Combine(_appEnvironment.WebRootPath, "images", newName);
                var stream = new FileStream(saveImg, FileMode.Create);
                await files[0].CopyToAsync(stream);
               
                currentUser.Picture = newName;
                repository.Update(currentUser);

                return Json(newName);
            }
            return Json("");
        }
    }
}

MVC Facebook/MVC Facebook/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVC_Facebook</title>
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


    @RenderSection("CSS", required: false)

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom  sticky-top  box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVC_Facebook</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - MVC_Facebook - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

MVC Facebook/MVC Facebook/Views/Shared/_MyLayout.cshtml
@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVC_Facebook</title>
    <link href="~/Content/jquery-ui.min.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    @*<link href="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.6.1/css/bootstrap4-toggle.min.css" rel="stylesheet">*@


</head>
<body class="bg-light">
    <header style="position:fixed;z-index:10;width:100%">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light btn-primary box-shadow mb-3">
            <div class="container">
                @if (SignInManager.IsSignedIn(User))
                {
                    <a class="navbar-brand text-white">MVC_Facebook</a>
                    if (!User.IsInRole("Admin"))
                    {
                        @Html.TextBox("strName", null, new { id = "txtSearch", size = 60, placeholder = "Enter Name", @class = "form-control col-6 ml-2" })
                    }
                }
                else
                {
                    <a class="navbar-brand text-white" asp-area="Identity" asp-page="/Account/MyLogin">MVC_Facebook</a>
                }
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_MyLoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3" style="position:relative;top:80px">

            @RenderBody()

        </main>
    </div>
    <br />
    <footer class="border-top footer text-muted" style="position:relative;top:80px">
        <div class="container">
            &copy; 2020 - MVC_Facebook - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    @*<script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    @*<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>*@
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/scripts/jquery.js" type="text/javascript"></script>
    <script src="~/Scripts/jquery-ui.min.js" type="text/javascript"></script>
    <script src="/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>

    @*<script src="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.6.1/js/bootstrap4-toggle.min.js"></script>*@


    @RenderSection("Scripts", required: false)

    <!-- Script for Search box -->
<script type="text/javascript">
    $("#txtSearch").autocomplete({
        focus: function (event, ui) {
            $(this).val(ui.item.fullName.firstName + " " + ui.item.fullName.lastName);
            return false;
        },
        source: function (request, response) {
            $.ajax({
                url: '@Url.Action("getName","User")',
                contentType: "application/json",
                data: { search: $("#txtSearch").val() },
                success: function (data) {
                    response(data);
                },
                error: function (xhr, status, error) {
                    alert("Erroooooooooooor");
                }
            });
        },
        select: function (e, i) {
            window.location.pathname = 'Profile/' + i.item.id;
        },
    }).autocomplete('instance')._renderItem = function (ul, item) {
        return $('<li>')
            .append("<div><img width='80' class='rounded' src='../images/" + item.picture + "' /><span>    " + item.fullName.firstName + " " + item.fullName.lastName + "</span></div>")
            .appendTo(ul);
    }

    function showComments(id) {
        $('#commentPost_' + id).load('../Comments/showCommentPost/' + id);
    }
    function deleteComment(btn, ValId) {
        $.ajax({
            url: '@Url.Action("Delete","Comments")',
            dataType: "json",
            data: { id: ValId },
            success: function (data) {
                setTimeout(function () {
                    showComments(data);
                }, 500);

                var numberOfComments = $('#numComments_' + data).html();
                $('#numComments_' + data).html(parseInt(numberOfComments) - 1);
            },
            error: function (xhr, status, error) {
                alert("Erroooooooooooor");
            }
        });
    };

    function addComment(postId) {
        valBody = $.trim($("#commentbox_" + postId).val());
        if (valBody != '') {
            $.ajax({
                method: 'POST',
                url: '@Url.Action("addComment","Comments")',
                dataType: "json",
                data: { PostID: postId, Body: valBody },
                success: function (data) {
                    setTimeout(function () {
                        showComments(data);
                        document.querySelector("#commentbox_" + postId).value = "";
                    }, 500);

                    var numberOfComments = $('#numComments_' + data).html();
                    $('#numComments_' + data).html(parseInt(numberOfComments) + 1);
                },
                error: function (xhr, status, error) {
                    alert("Error!");
                }
            });
        }
    };

</script>

</body>
</html>

MVC Facebook/MVC Facebook/Views/Shared/_MyLoginPartial.cshtml
@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager

<ul class="navbar-nav">

    @if (SignInManager.IsSignedIn(User))
    {

        if (User.IsInRole("Normal User"))
        {
            <li class="nav-item">
                <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-white" asp-area="" asp-controller="Profile" asp-action="Index" asp-route-id="@UserManager.GetUserId(User)">
                    Profile
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-white" asp-area="Identity" asp-page="/Account/Manage/ChangePassword" title="Manage">
                    Settings
                </a>
            </li>
            <li class="nav-item">
                <form class="form-inline" asp-area="Identity" asp-page="/Account/Logout">
                    <button type="submit" class="nav-link text-white btn btn-link">Logout</button>
                </form>
            </li>

        }
        else if (User.IsInRole("Admin"))
        {
            <li>
                <a class="nav-link text-white" asp-controller="Admin" asp-action="Index">
                    Users
                </a>
            </li>
            <li>
                <a class="nav-link text-white" asp-controller="Admin" asp-action="AddNewRole">
                    Roles
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-white" asp-area="Identity" asp-page="/Account/Manage/ChangePassword" title="Manage">
                    Settings
                </a>
            </li>
            <li class="nav-item">
                <form class="form-inline" asp-area="Identity" asp-page="/Account/Logout">
                    <button type="submit" class="nav-link btn btn-link text-white">Logout</button>
                </form>
            </li>

        }
    }
    else
    {
        <li class="nav-item">
            <a class="nav-link text-white" asp-area="Identity" asp-page="/Account/Register">Register</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-white" asp-area="Identity" asp-page="/Account/MyLogin">Login</a>
        </li>
    }
</ul>